### PR TITLE
fix: drawable shape fade in compose

### PR DESCRIPTION
**Pull request by dostalleos**
Fixed `DrawableShape` fade-out animation in the Compose ConfettiView.
Currently, it doesn't work as expected. It juts flickers somehow.

### CODE REVIEW

**Comment by DanielMartinus** [comment]
Hi @dostalleos, thanks for opening a Pull Request. Could you please elaborate a little more on why you're fixing this alpha? Running some tests I don't see any issues with the Alpha.

**Comment by dostalleos** [comment]
@DanielMartinus Unfortunately, I do not remember exactly. I think that the particles were flickering before being invisible. It was happening only when using `DrawableShape`.

**Comment by DanielMartinus** [comment]
Thanks @dostalleos. Do you remember on what device/os type this happened?

**Comment by dostalleos** [comment]
@DanielMartinus Unfortunately not. But I think it was happening on all the devices we tested.

**Comment by DanielMartinus** [comment]
When validating this fix https://github.com/DanielMartinus/Konfetti/issues/298 I was able to reproduce your issue when using a DrawableShape and Alpha.

**Comment by DanielMartinus** [comment]
Fixes has been released in version 2.0.3, thanks for your contribution!

**Pull request merged**
