### PR TITLE
Replace withFrameMillis with withInfiniteAnimationFrameMillis to run …

### LINKED ISSUE #306: Error for a composable with a KonfettiView on instrumented android test
An error occurred in an instrumented Android test on a composable with a KonfettiVIew inside 
```
androidx.compose.ui.test.junit4.android.ComposeNotIdleException: Idling resource timed out: possibly due to compose being busy.
IdlingResourceRegistry has the following idling resources registered:
- [busy] ComposeIdlingResource is busy due to pending recompositions.
- Note: Timeout on pending recomposition means that there are most likely infinite re-compositions happening in the tested code.

```
Any idea to avoid this error ?

### PR DESCRIPTION
**Pull request by lupuuss**
Closes #306

### CODE REVIEW

**Comment by matthewbartos** [comment]
@DanielMartinus can we merge this one?

**Comment by DanielMartinus** [comment]
@matthewbartos hey, thanks for tagging me. For sure, could you give me a little rundown on how this is fixing the issue?

**Comment by matthewbartos** [comment]
Please see work from @crowleysimon and @lupuuss - they claim that this change fixes failing UI tests:
```
Compose did not get idle after 48903 attempts in 60 SECONDS. Please check your measure/layout lambdas, they may be causing an infinite composition loop. Or set Espresso's master idling policy if you require a longer timeout. The following Idle Conditions failed .
androidx.test.espresso.AppNotIdleException
```

**Review by DanielMartinus — APPROVED** [review]
Tested and working as expected

**Comment by matthewbartos** [comment]
Thank you @DanielMartinus - when do you anticipate the next release? 🙂

**Comment by DanielMartinus** [comment]
@matthewbartos I'm running into some issues publishing the release and need to set aside time to figure out exactly what's going on. Over the next few days, I'll try to schedule some time for that. I'll keep you updated here

**Comment by DanielMartinus** [comment]
@matthewbartos I've put out a new release v2.0.5. Will take a couple minutes to become available

**Comment by matthewbartos** [comment]
I appreciate it @DanielMartinus!

**Pull request merged**
