### PR TITLE
Add support for Text shape

### PR DESCRIPTION
**Pull request by alexbirkett**
The idea is to use this primarily for emojis but any text will work

Update google-play-demo app

Ic_laughing.xml comes from https://www.flaticon.com/free-icon/laughing_2274453 and should be attributed according to instructions on that page.

### CODE REVIEW

**Comment by DanielMartinus** [comment]
@alexbirkett when I tested it I noticed a pretty big FPS drop, it seems to have a hard time rendering text. Also there's not 3D rotation support which would be something that I'd like to see supported when such a feature is added.

Perhaps, if you want to use emoji's. Is it also possible to download a vector or png image of that emoji somewhere and render it with a `DrawableShape`? That way it will be rendered without any fps issues and it will also have 3D rotation support and other things.

**Comment by alexbirkett** [comment]
Thanks for looking at this @DanielMartinus !
If the Emojis are used sparingly the frame-rate is acceptable.
Using a `DrawableShape` is not possible for my use-case as the emojis come from user input.
3D rotation is not desirable for my use-case but maybe it could be turned on an off on a per `Shape` basis?

If I can improve the framerate and and make the rotation configurable, is this PR interesting? If not I'll live with the fork.

**Comment by DanielMartinus** [comment]
> If I can improve the framerate and and make the rotation configurable, is this PR interesting? If not I'll live with the fork.

Yes, that would be great! Looking at the use-cases I would like to try to cover larger audiences and keeping the performance high is an important aspect of that too.

**Comment by DanielMartinus** [comment]
Closing this for now. For now I'd like to stick to a solution fits all if we add features like this. Feel free to fork and release for your own project if necessary.

**Pull request closed without merging**
